CREATE DATABASE TRA1
USE TRA1
go

CREATE TABLE Loaisp
(
  Maloaisp NVARCHAR(100) NOT NULL PRIMARY KEY,
  Tenloaisp NVARCHAR(255)  NULL
);

CREATE TABLE Thuonghieu
(
  Math NVARCHAR(100) NOT NULL PRIMARY KEY,
  Tenth NVARCHAR(255) NULL
);

CREATE TABLE Khachhang
(
  MaKH NVARCHAR(255) NOT NULL PRIMARY KEY,
  TenKH NVARCHAR(255) NULL,
  Diachi NVARCHAR(255) NULL,
  SDT NVARCHAR(255)  NULL,
  Username_khach NVARCHAR(255) NULL,
  Password_khach NVARCHAR(255) NULL
);

CREATE TABLE Hoadonban
(
  SoHDB NVARCHAR(255) NOT NULL PRIMARY KEY,
  MaKH NVARCHAR(255) NULL,
  Ngayban NVARCHAR(255) NULL,
  Tongtien FLOAT  NULL,
  FOREIGN KEY (MaKH) REFERENCES Khachhang(MaKH)
);

CREATE TABLE Admin
(
  Username VARCHAR(255) NOT NULL PRIMARY KEY,
  Password VARCHAR(255)  NULL
);

CREATE TABLE Sanpham
(
  MaSP NVARCHAR(100) NOT NULL PRIMARY KEY,
  TenSP NVARCHAR(100) NULL,
  Maloaisp NVARCHAR(100)  NULL,
  Math NVARCHAR(100)  NULL,
  Giaban INT  NULL,
  Mota NVARCHAR(255)  NULL,
  Trongluong NVARCHAR(255) NULL,
  Cachpha NVARCHAR(255)  NULL,
  Ngaytao NVARCHAR(255) NULL,
  Username VARCHAR(255)  NULL,
  AnhSP NVARCHAR(255)  NULL,
  FOREIGN KEY (Maloaisp) REFERENCES Loaisp(Maloaisp),
  FOREIGN KEY (Math) REFERENCES Thuonghieu(Math),
  FOREIGN KEY (Username) REFERENCES Admin(Username)
);

CREATE TABLE Tintuc
(
  MaTT NVARCHAR(255) NOT NULL PRIMARY KEY,
  Tieude NVARCHAR(255)  NULL,
  Gioithieu NVARCHAR(255)  NULL,
  Ngaytaott NVARCHAR(255) NULL,
  Username VARCHAR(255)  NULL,
  AnhTT NVARCHAR(255) NULL,
  FOREIGN KEY (Username) REFERENCES Admin(Username)
);

CREATE TABLE Nghenhan
(
  MaNN NVARCHAR(255) NOT NULL PRIMARY KEY,
  Tennghenhan NVARCHAR(255) NULL,
  AnhNN NVARCHAR(255) NULL,
  Thongtin NVARCHAR(255) NULL,
  Username VARCHAR(255)  NULL,
  FOREIGN KEY (Username) REFERENCES Admin(Username)
);

CREATE TABLE Chitiethdb
(
  SoHDB NVARCHAR(255) NOT NULL PRIMARY KEY, 
  MaSP NVARCHAR(100) NOT NULL,
  SL INT  NULL,
  Giamua FLOAT NULL,
  FOREIGN KEY (MaSP) REFERENCES Sanpham(MaSP),
  FOREIGN KEY (SoHDB) REFERENCES Hoadonban(SoHDB)
);